name: Conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1')}}
  status-check:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - run: echo "Hello"
        if: ${{ failure() }}
